export const  CART_ADD_ITEM = 'ART_ADD_ITEM';
export const  CART_DELETE_ITEM = 'ART_DELETE_ITEM';
export const CART_CLEAR_ITEMS = 'CART_RESET'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'