export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'


export const ORDER_PAID_REQUEST = 'ORDER_PAID__REQUEST'
export const ORDER_PAID_SUCCESS = 'ORDER_PAID__SUCCESS'
export const ORDER_PAID_FAIL = 'ORDER_PAID__FAIL'
export const ORDER_PAID_RESET = 'ORDER_PAID__RESET'